.TH SPAG 1 2024-03-31
.SH NAME
\fBspag\fR \- simple password generator
.SH SYNOPSIS
.B spag
[\fIOPTION\fR]...
.SH DESCRIPTION
.B spag
(Simple PAssword Generator) is a simple command-line password generator written in C. By default, it prints to standard output a 20 character random password, that can include majuscules, minuscules, numbers and symbols.
.SH OPTIONS
.TP
.BR \-h ", " \-\-help
display the list of options and exits
.TP
.BR \-l ", " \-\-length "=" \fILENGTH
set the \fILENGTH\fR of the password(s)
.TP
.BR \-m ", " \-\-no\-minuscules
disable minuscule characters
.TP
.BR \-M ", " \-\-no\-majuscules
disable majuscule characters
.TP
.BR \-n ", " \-\-no\-numbers
disable numbers
.TP
.BR \-q ", " \-\-quantity "=" \fIQUANTITY
set the \fIQUANTITY\fR of passwords to be generated
.TP
.BR \-s ", " \-\-no\-symbols
disable symbols
.SH AUTHOR
Written by Lucas Melo Sanginetto <\fIlucamsanginetto@outlook.com\fR>
